### ISSUE TITLE
Feature Request - Update to Storybook 6.0

### ISSUE THREAD

**Issue by litan1106** [ux-engineer/boilerplate-ts-vue-storybook-tailwind-postcss#1]
Storybook 6.0.21 is available.

**Comment by ux-engineer** [comment]
@litan1106 thanks for following up on this repository. I will continue working on Storybook with Vue in TypeScript later this year. Currently I've done Vue 3.0 upgrade for my application frame, however, there remains a few issues to be solved before I can consider this Vue 3 upgrade to be ready...
